Implementation of the basic architecture
freelkee/Car-Manager pull request #1
Opened 2023-08-18 17:28 UTC by freelkee

2023-08-19 03:56 UTC, MrZMorgan requested changes

2023-08-19 03:56 UTC, MrZMorgan commented on src/main/java/com/freelkee/carmanager/controller/CarController.java
> +        List<Car> cars = carService.getCars();
У нас Java 11 поэтому можем использовать объявлять переменные через var, так же все переменные должны быть по максимум final. Проверь это во всем проекте.

2023-08-19 03:56 UTC, MrZMorgan commented on src/main/java/com/freelkee/carmanager/controller/CarController.java
> +    public String getCars(Model model) {
Аргументы методов так же должны быть максимально final, поправь во всем проекте

2023-08-19 03:56 UTC, MrZMorgan commented on src/main/java/com/freelkee/carmanager/controller/CarController.java
> +    @GetMapping("/cars")
Маппинг неудачный. Лучше сделать маппинг /car на уровне кантроллера, а тут тогда маммпинга не будет

2023-08-19 03:56 UTC, MrZMorgan commented on src/main/java/com/freelkee/carmanager/controller/CarController.java
> +    @GetMapping("/car/{id}")
А здесь тогда будет просто /{id}

2023-08-19 03:56 UTC, MrZMorgan commented on src/main/java/com/freelkee/carmanager/controller/OwnersController.java
> +    @GetMapping("/owners")
/owner вынеси на уровень контроллера

2023-08-19 03:56 UTC, MrZMorgan commented on src/main/java/com/freelkee/carmanager/controller/OwnersController.java
> +    private final OwnerService ownerService;
Добавь перенос строки до и перенос строки после. Так же и в другиз местах где поля класса

2023-08-19 03:56 UTC, MrZMorgan commented on src/main/java/com/freelkee/carmanager/controller/SellerController.java
> +    @GetMapping("/sellers")
Маппинг сделай по аналогии с комменатриями к  CarController

2023-08-19 03:56 UTC, MrZMorgan commented on src/main/java/com/freelkee/carmanager/repository/CarRepository.java
> +    List<Car> findAll();
Нет нужны писать методы которые ужу есть в репозитории

2023-08-19 03:56 UTC, MrZMorgan commented on src/main/java/com/freelkee/carmanager/repository/CarRepository.java
> +@Repository
Тут аннотация тоже не нужна, из за того что интерфейс наследуется от JpaRepository то он будет бином

2023-08-19 03:56 UTC, MrZMorgan commented on src/main/java/com/freelkee/carmanager/repository/SellerRepository.java
> +    Optional<Seller> findById(Long id);
Тоже самое - это методы есть в репозитории

2023-08-19 03:56 UTC, MrZMorgan commented on src/main/java/com/freelkee/carmanager/service/CarService.java
> +    public CarService(CarRepository carRepository, OwnerRepository ownerRepository, AvailabilityRepository availabilityRepository) {
Если строка длинней листа в идее (там есть вертикальная линия то переноси вот так)


        CarRepository carRepository, 
        OwnerRepository ownerRepository, 
        AvailabilityRepository availabilityRepository

2023-08-19 03:56 UTC, MrZMorgan commented on src/main/java/com/freelkee/carmanager/service/CarService.java
> +    @Autowired
Если инжект через конструктор то Autowired убирай везде

2023-08-19 03:56 UTC, MrZMorgan commented on src/main/java/com/freelkee/carmanager/service/CarService.java
> +        Optional<Car> carOptional = carRepository.findById(id);
Используй вот этот метод getReferenceById, или использую более точный эксепшн, например EntityNotFoundException

2023-08-19 03:56 UTC, MrZMorgan commented on src/main/java/com/freelkee/carmanager/service/CarService.java
> +            return ownerRepository.findAllByCar(carOptional.get());
Даже если тело цикла в 1 строку приято всегда писать в {   }

2023-08-19 03:56 UTC, MrZMorgan commented on src/main/java/com/freelkee/carmanager/service/CarService.java
> +    }
И если используешь опшнал, то у него есть куча методов и весь твой метод можно вот так записать

    public List<Owner> getOwners(final Long id) {
        return carRepository
            .findById(id)
            .map(ownerRepository::findAllByCar)
            .orElseThrow(() -> new EntityNotFoundException(String.format("Car %d does not exist", id)));
    }

2023-08-19 03:56 UTC, MrZMorgan commented on src/main/java/com/freelkee/carmanager/service/CarService.java
> +            return sellers;
Это можно переписать с помощью stream

2023-08-19 03:56 UTC, MrZMorgan commented on src/main/java/com/freelkee/carmanager/service/OwnerService.java
> +        return ownerRepository.findAll().stream().map(OwnerResponse::of).collect(Collectors.toList());
В стримах операции принто писать с новой сторки

    public List<OwnerResponse> getOwners() {
        return ownerRepository.findAll().stream()
            .map(OwnerResponse::of)
            .collect(Collectors.toList());
    }

2023-08-19 03:56 UTC, MrZMorgan commented on src/main/java/com/freelkee/carmanager/service/SellerService.java
> +        this.availabilityRepository = availabilityRepository;
Поправь форматирование

    public SellerService(
        final SellerRepository sellerRepository,
        final AvailabilityRepository availabilityRepository
    ) {
        this.sellerRepository = sellerRepository;
        this.availabilityRepository = availabilityRepository;
    }

2023-08-19 03:56 UTC, MrZMorgan commented on src/main/java/com/freelkee/carmanager/service/SellerService.java
> +        } else throw new RuntimeException("Seller does not exist");
То же самое что и в CarService

2023-08-19 03:56 UTC, MrZMorgan commented on src/main/java/com/freelkee/carmanager/service/SellerService.java
> +}
То же самое что и в CarService

2023-08-19 03:56 UTC, MrZMorgan commented on src/main/java/com/freelkee/carmanager/entity/Availability.java
> +public class Availability {
Этот класс не нужен. Тебе нужно настроить связи между таблицами cars и sellers метод из AvailabilityRepository вынести в соответствующие репозитории запрос реализовать через @Query
https://www.baeldung.com/spring-data-jpa-query

2023-08-19 03:56 UTC, MrZMorgan commented on src/main/java/com/freelkee/carmanager/repository/AvailabilityRepository.java
> +public interface AvailabilityRepository extends JpaRepository<Availability, Long> {
Смотри комментарий к Availability

2023-08-19 03:56 UTC, MrZMorgan commented on src/main/java/com/freelkee/carmanager/entity/Owner.java
> +    private Car car;
Связи не прописаны со стороны Car

2023-08-19 03:56 UTC, MrZMorgan commented on src/main/java/com/freelkee/carmanager/response/AvailabilityResponse.java
> +                .build();
В настройках роматирования джавы в идее поставь пробелы везде по 4

2023-08-20 01:16 UTC, freelkee commented on src/main/java/com/freelkee/carmanager/entity/Availability.java
> +public class Availability {
Только на Native что-то заработало, и то не с первого раза. Я помню, что ты говорил, что приложение не должно знать об устройстве БД, но пока так только так получилось.

2023-08-20 01:17 UTC, freelkee commented on src/main/java/com/freelkee/carmanager/response/AvailabilityResponse.java
> +                .build();
Тут не совсем понял, вроде в настройках так и стоит

2023-08-20 01:18 UTC, freelkee commented on src/main/java/com/freelkee/carmanager/controller/CarController.java
> +        List<Car> cars = carService.getCars();
Ещё проще сделал

2023-08-20 01:20 UTC, freelkee commented on src/main/java/com/freelkee/carmanager/service/CarService.java
> +    }
После того, как убрал, класс Availability, это не пригодилось, но на заметку взял

2023-08-20 01:21 UTC, freelkee commented on src/main/java/com/freelkee/carmanager/service/CarService.java
> +            return sellers;
Переписал, но тоже не пригодилось

2023-08-20 09:12 UTC, MrZMorgan requested changes

2023-08-20 09:12 UTC, MrZMorgan commented on src/main/java/com/freelkee/carmanager/response/OwnerResponse.java
> +        } else return ownerResponseBuilder.carId(owner.getCar().getId()).build();
Тут тоже тело добавляй

2023-08-20 09:12 UTC, MrZMorgan commented on src/main/java/com/freelkee/carmanager/service/CarService.java
> +            final SellerRepository sellerRepository
Выставь в идее форматирование на 4 пробела

2023-08-20 09:12 UTC, MrZMorgan commented on src/main/java/com/freelkee/carmanager/service/OwnerService.java
> +    public OwnerService(OwnerRepository ownerRepository) {
Проверь по проекту final

2023-08-20 09:12 UTC, MrZMorgan commented on src/main/resources/schema.sql
> +CREATE TABLE IF NOT EXISTS availability
Переименуй в sellers_to_cars

2023-08-20 09:12 UTC, MrZMorgan commented on src/main/java/com/freelkee/carmanager/service/CarService.java
> +        return sellerRepository.findAllByCar(id);
У тебя настроено отношение между таблицами поэтому можешь просто сделать 
return carRepository.getReferenceById(id).getSellers();

2023-08-20 09:12 UTC, MrZMorgan commented on src/main/java/com/freelkee/carmanager/service/CarService.java
> +    }
Здесь так же разв связи настроены то все сделает хибернейт

    public List<Car> getCars(final Long id) {
        return sellerRepository.getReferenceById(id).getCars();
    }

2023-08-20 09:12 UTC, MrZMorgan commented on src/main/java/com/freelkee/carmanager/service/CarService.java
> +    public List<Seller> getSellers(final Long id) {
id для аргумента метода не удачное название, по нему не понятно что мы делаем. Называй аргументы озознано, в данном случае это carId

2023-08-20 09:12 UTC, MrZMorgan commented on src/main/java/com/freelkee/carmanager/response/OwnerResponse.java
> +        } else return ownerResponseBuilder.carId(owner.getCar().getId()).build();
public static OwnerResponse of(final Owner owner) {
        return OwnerResponse.builder()
            .id(owner.getId())
            .name(owner.getName())
            .carId(
                Optional.ofNullable(owner.getCar())
                    .map(Car::getId)
                    .orElse(null))
            .build();
    }

2023-08-20 09:12 UTC, MrZMorgan commented on src/main/java/com/freelkee/carmanager/controller/CarController.java
> +        model.addAttribute("cars", carService.getCars());
Тут нужно dto возвращать, а не сущности

2023-08-20 09:12 UTC, MrZMorgan commented on src/main/java/com/freelkee/carmanager/controller/CarController.java
> +        model.addAttribute("sellers", carService.getSellers(id))
Тут нужно dto возвращать, а не сущности

2023-08-20 19:55 UTC, merged